Disable Python 3.8-3.10 in the test and build jobs
These versions must be disabled to the following dependency issue:

ERROR: Cannot install pshtt because these package versions have conflicting dependencies.

The conflict is caused by:
    sslyze 2.1.4 depends on nassl<2.3.0 and >=2.2.0
    sslyze 2.1.3 depends on nassl<2.3.0 and >=2.2.0